SUPABASE_URL = "https://ldagdlotggsrvsspnfmr.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkYWdkbG90Z2dzcnZzc3BuZm1yIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MjQ5ODcwNywiZXhwIjoyMDY4MDc0NzA3fQ.ryoPu4qHS7v28q94deSi9QAw8MiLNBrrQkn8petPsXo"
